-- AMF Révision : schéma Supabase
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  theme text not null,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  correct_answer int not null check (correct_answer between 0 and 2),
  explanation text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_answer int not null check (selected_answer between 0 and 2),
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role) values (new.id, 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select to authenticated
using (auth.uid() = id);

drop policy if exists "questions authenticated read" on public.questions;
create policy "questions authenticated read" on public.questions for select to authenticated using (true);

drop policy if exists "questions admin insert" on public.questions;
create policy "questions admin insert" on public.questions for insert to authenticated
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "questions admin update" on public.questions;
create policy "questions admin update" on public.questions for update to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "questions admin delete" on public.questions;
create policy "questions admin delete" on public.questions for delete to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "attempts own read" on public.attempts;
create policy "attempts own read" on public.attempts for select to authenticated using (auth.uid()=user_id);

drop policy if exists "attempts own insert" on public.attempts;
create policy "attempts own insert" on public.attempts for insert to authenticated with check (auth.uid()=user_id);

grant select on public.profiles to authenticated;
grant select on public.questions to authenticated;
grant insert,update,delete on public.questions to authenticated;
grant select,insert on public.attempts to authenticated;
